### PR TITLE
making timestamp deserialization consistent

### PR DESCRIPTION
**Pull request by or-shachar**
fixing #17

### CODE REVIEW

**Comment by or-shachar** [comment]
Not sure the failure is related to my change.

**Comment by or-shachar** [comment]
Hi @khmarbaise . Appreciate your review.
Thanks!

**Comment by or-shachar** [comment]
@rfscholte maybe you can help here?

**Comment by rfscholte** [comment]
With a quick view this fix seems okay, would be nice if this could be confirmed with a unittest

**Comment by stephenc** [comment]
LGTM
-- 
Sent from my phone

**Pull request merged**
